### ISSUE TITLE
How to thinned the posterior samples?

### ISSUE THREAD

**Issue by yanyuechuixue** [gwastro/pycbc-inference-paper#1]
I use the script in run_files and get "gw150914_inference.hdf" file, 
but it is not same with "gw150914_posteriors_thinned.hdf".

Could you introduce the method of how to thinned the posterior samples?

**Comment by cdcapano** [comment]
You need to run `pycbc_inference_extract_samples` on `gw150914_inference.hdf` file, but I'm not sure what thin interval settings @soumide1102 used. @soumide1102 can you comment?

It would be good to add the extract samples command to the repo, either as separate scripts, or as an addendum to the run scripts.

**Comment by soumide1102** [comment]
Hi @yanyuechuixue The "gw150914_inference_thinned.hdf" contains the thinned chains or independent samples extracted from the chains stored in the output file from the run "gw150914_inference.hdf". I've now added the commands for thinning the chains in scripts called`extract_independent_samples.sh` in the events folders under `run_files`. You'll have to run the script for thinning with a version of PyCBC that is post v1.9.4 ( https://github.com/gwastro/pycbc/releases ).

**Comment by yanyuechuixue** [comment]
Thank you!
